# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-05 17:48
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='insta_image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
            preserve_default=False,
        ),
    ]
