# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-05 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20200105_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='insta_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_photo',
        ),
    ]
