# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-24 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20191225_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Comment'),
        ),
    ]
