# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-05 20:54
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20200105_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='insta_image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
