# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-27 06:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0014_auto_20191226_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=70)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['username']},
        ),
        migrations.RemoveField(
            model_name='likes',
            name='admirer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        # migrations.AlterField(
        #     model_name='likes',
        #     name='image_id',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        # ),
        
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Comment'),
        ),
    ]
