# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-27 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_auto_20191227_0900'),
    ]

    operations = [
       
    ]
