# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-27 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0018_auto_20191227_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='admirer',
            new_name='imagecomment',
        ),
       
        migrations.AlterField(
            model_name='image',
            name='thoughts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Comment'),
        ),
    ]
