# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-28 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0020_auto_20191228_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='imagecomment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
       
        migrations.RemoveField(
            model_name='likes',
            name='image_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='images.Image'),
        ),
        migrations.AddField(
            model_name='comment',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
       
    ]
