# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-31 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0022_auto_20191228_1934'),
    ]

    operations = [  
        migrations.RemoveField(
            model_name='likes',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
