# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-03 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0025_auto_20200103_1235'),
    ]

    operations = [
        
        
        
    ]
